### PR TITLE
Added ability to customize number of attachment fields using :slack_fields

### PR DESCRIPTION
**Pull request by korotovsky**

### CODE REVIEW

**Comment by seenmyfate** [comment]
@korotovsky thanks for this, look like a good addition - would you be able to update the failing specs? I suspect it's just missing the new `:slack_fields` key in the context hash.

**Comment by korotovsky** [comment]
@seenmyfate Seems to be fixed!

**Comment by seenmyfate** [comment]
Awesome, thanks :metal:

**Comment by seenmyfate** [comment]
This now available via Rubygems as [2.7.0](https://rubygems.org/gems/capistrano-slackify/versions/2.7.0)

**Comment by korotovsky** [comment]
Cool! Thanks a lot.

**Pull request merged**
