### PR TITLE
Silence curl

### PR DESCRIPTION
**Pull request by cheald**
Get rid of the ugly progress bars!

### CODE REVIEW

**Comment by seenmyfate** [comment]
@cheald thanks for that, would you be able to add it to the `finished` task as well?  I'll look into why CI is failing, nothing here should be causing that

**Comment by cheald** [comment]
Whoops. Not sure how I missed that. Done!

**Comment by seenmyfate** [comment]
Great, thanks :+1:

**Comment by seenmyfate** [comment]
This change is now available from Rubygems in [v2.6.1](https://rubygems.org/gems/capistrano-slackify/versions/2.6.1)

**Pull request merged**
